### ISSUE TITLE
Não fez nada !!

### ISSUE THREAD

**Issue by ttsoares** [MBrunoS/prisma-next-crud-generator#33]
Seguindo o README este sistema não faz nada...

**Comment by MBrunoS** [comment]
Olá @ttsoares! Agradeço por ter chegado aqui e testado o package.  Mas me desculpe, sei que ele está desatualizado, e talvez até precise ser refeito. Mas eu precisaria dedicar um tempo pra ele, atualizar pra ter compatibilidade com o diretório `app` do Next 13, etc...

Eu acabei de testar e vi que a configuração no README está errada, provavelmente devido à atualizações. 
```prisma
// schema.prisma
generator crud {
  provider = "node ./node_modules/prisma-next-crud-generator"
  output   = "../src" // Optional: the output folder for the generated files
}
```
Tirando isso, consegui rodar.  Você instalou o Prisma e colocou models? É só o que precisa pra rodar.
