### ISSUE TITLE
Methods in Prisma are camelCase not lowercase

### ISSUE THREAD

**Issue by dmoibm** [MBrunoS/prisma-next-crud-generator#46]
Prisma recommends PascalCase for models. Prisma generates a methode clientProtocol from a model called ClientProtocol.
But the CRUD Generator calls clientprotocol. For example in src\app\clientprotocols\page.tsx line 9 is

`const clientprotocols = await prisma.clientprotocol.findMany();`

This should be 

`const clientprotocols = await prisma.clientProtocol.findMany();`

**Comment by MBrunoS** [comment]
Thank you for spotting this, I'm gonna fix it soon.

**Comment by MBrunoS** [comment]
@dmoibm I fixed this issue, and handled plural/singular cases as well. Please let me know if you find any more bugs!

**Comment by dmoibm** [comment]
> @dmoibm I fixed this issue, and handled plural/singular cases as well. Please let me know if you find any more bugs!

I updatet the generator to version 1.3.0 but now I get "Error: spawn npx next-crud-generator ENOENT" if I run `npx prisma generate`. If I run `npx next-crud-generator` I get this error:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/next-crud-generator - Not found
npm ERR! 404
npm ERR! 404  'next-crud-generator@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
