### ISSUE TITLE
Prisma schema loaded from prisma\schema.prisma Error: spawn prisma-next-crud-generator ENOENT

### ISSUE THREAD

**Issue by superstonne** [MBrunoS/prisma-next-crud-generator#53]
Do you know what's the problem?
Prisma schema loaded from prisma\schema.prisma
Error: spawn prisma-next-crud-generator ENOENT

**Comment by MBrunoS** [comment]
@superstonne in your `schema.prisma`, could you change the line `provider = "prisma-next-crud-generator"` to `provider = "next-crud-generator"`?

There's a little problem that I'm gonna patch soon, a kind of typo in the generator package.json. But I believe that doing what I said above will solve for you.

**Comment by superstonne** [comment]
thank you, it's working. but I can't run App directly, looks I need to copy files manually to an existing nextjs project, right?
![image](https://github.com/MBrunoS/prisma-next-crud-generator/assets/7440390/ab242395-fff8-451c-b2ec-56109a4da466)

**Comment by MBrunoS** [comment]
Right now, it should be possible to use as described in the updated documentation: `npx prisma-next-crud-generator`

**Comment by superstonne** [comment]
I see, really appreciate.
